### ISSUE TITLE
Julia v0.6.4 has been released

### ISSUE THREAD

**Issue by samoconnor** [docker-library/julia#19]
https://discourse.julialang.org/t/julia-v0-6-4-has-been-released/12305

**Comment by tianon** [comment]
Looks like the automated update has been failing due to 0.6.4 no longer including release builds for the arches they call `armv7l` and `aarch64` -- I've asked upstream in https://github.com/JuliaLang/julia/issues/27174#issuecomment-404615503 if this was intentional, but it might make more sense to ask directly in that release thread on Discourse.
