### ISSUE TITLE
Error: No such image: julia:1.0

### ISSUE THREAD

**Issue by cossio** [docker-library/julia#27]
I'm getting the following error on Gitlab's CI:

```
Using Docker executor with image julia:1.0 ...
Pulling docker image julia:1.0 ...
ERROR: Preparation failed: Error: No such image: julia:1.0 (executor_docker.go:175:0s)
```

**Comment by yosifkit** [comment]
Yeah the linux builds failed because of https://bugs.debian.org/913614, but the windows builds succeeded. So this is a case of https://github.com/docker-library/official-images/issues/3835. It will be fixed by https://github.com/docker-library/official-images/pull/5070, but it will take quite a while for the servers to get through all the builds.

To work around it use one of the simple tags listed on the Hub description that don't share a manifest with a windows image, like `julia:1.0-stretch`. 

Note: `1.0.2-stretch` will still fail since that is the build that failed because of the Debian bug.
