### ISSUE TITLE
Add docker to the download page of julia

### ISSUE THREAD

**Issue by henrykironde** [docker-library/julia#28]
The download page of Julia https://julialang.org/downloads/ should include a link to using docker.

Something like
#### Using Docker images
Pull [docker julia](https://hub.docker.com/_/julia/) image 
`docker pull julia`

**Comment by fredrikekre** [comment]
Probably more suited for https://github.com/JuliaLang/www.julialang.org.

**Comment by tianon** [comment]
Indeed, that would be a request that should be made to the maintainers of that page -- we aren't in contact with anyone who can do anything about that (although if they see this and would like to be more involved in the maintenance of this image, we'd certainly welcome them! :heart:)

Closing since there's nothing we can do here.

**Comment by henrykironde** [comment]
👍 Thanks folks

**Comment by fredrikekre** [comment]
> You're definitely welcome (and encouraged! smile) to be as active here as you like, and we'd be happy to co-maintain or even turn over maintenance of the image entirely if you think it would be helpful for the Julia project at large.

Thanks, I am watching from a distance for now, but feel free to ping me with any specific questions. We are happy for all help, and you people are doing a great job maintaining these images!
