### ISSUE TITLE
Update to 1.5.1?

### ISSUE THREAD

**Issue by blairdrummond** [docker-library/julia#49]
New release is out! :-) 

https://github.com/JuliaLang/julia/tree/v1.5.1

**Comment by ImreSamu** [comment]
> New release is out! :-)

imho: Still waiting for the 1.5.1 binaries  https://julialang.org/downloads/
see 
* https://github.com/docker-library/julia/blob/master/1.5/buster/Dockerfile#L49

**Comment by tianon** [comment]
Yep -- the release is tagged, but since binaries aren't released yet, we haven't bumped yet (and can't). :sweat_smile:

Once the binaries are released, the bump will be automated by @docker-library-bot, after which it will follow through https://github.com/docker-library/faq#an-images-source-changed-in-git-now-what (as usual). :+1:
