### ISSUE TITLE
Update to 1.9.0

### ISSUE THREAD

**Issue by benz0li** [docker-library/julia#77]
Julia v1.9.0 has been released:

* Source: https://github.com/JuliaLang/julia/releases/tag/v1.9.0
* Binaries: https://julialang.org/downloads

**Comment by benz0li** [comment]
Not sure if v1.8 is going to be the new LTS or not: https://discourse.julialang.org/t/new-julia-lts-are-many-using-the-current-julia-1-6-lts/93919/8

FYI @tianon

**Comment by fredrikekre** [comment]
(There are no plans to make 1.8 LTS. There have been (vague) discussions to make 1.10 LTS, but no concrete plans.)

**Comment by iamed2** [comment]
Is there a strong reason to remove old versions? Even though Julia doesn't get updates, the OS does, and there are security reasons to want to update the OS even if the Julia version doesn't change. Is there downward pressure on the amount of images to build?

It would be nice to continue using the official Julia images rather than build our own using the exact same template.
